SELECT
	  COLUMNS.ATTNUM
	, TABLES.RELNAME AS TABLE_NAME
	, COLUMNS.ATTNAME AS COLUMNS_NAME
	, TABLE_COMMENT.DESCRIPTION AS TABLES_COMMENT
	, COMMENT.DESCRIPTION AS COLUMNS_COMMENT
FROM
	 PG_STAT_ALL_TABLES TABLES
INNER JOIN
	PG_ATTRIBUTE COLUMNS
ON
	COLUMNS.ATTRELID = TABLES.RELID
	AND COLUMNS.ATTNUM > 0
LEFT JOIN
	PG_DESCRIPTION TABLE_COMMENT
ON 
	TABLE_COMMENT.OBJOID = COLUMNS.ATTRELID 
	AND TABLE_COMMENT.OBJSUBID = 0
LEFT JOIN
	PG_DESCRIPTION COMMENT
ON 
	COMMENT.OBJOID = COLUMNS.ATTRELID 
	AND COMMENT.OBJSUBID = COLUMNS.ATTNUM
WHERE 
	TABLES.SCHEMANAME = 'public'
ORDER BY
	  TABLE_NAME
	, COLUMNS.ATTNUM
