SELECT
	  TABLES.RELNAME AS TABLE_NAME
	, COLUMNS.ATTNAME AS COLUMNS_NAME
	, COMMENT.DESCRIPTION AS COLUMNS_COMMENT
FROM
	 PG_STAT_ALL_TABLES TABLES
INNER JOIN
	PG_DESCRIPTION COMMENT
ON 
	TABLES.RELID = COMMENT.OBJOID
	AND COMMENT.OBJSUBID > 0
INNER JOIN
	PG_ATTRIBUTE COLUMNS
ON
	COLUMNS.ATTRELID = COMMENT.OBJOID
	AND COLUMNS.ATTNUM = COMMENT.OBJSUBID
ORDER BY
	COMMENT.OBJSUBID