SELECT
	  TABLES.RELNAME AS TABLE_NAME
	, COLUMNS.ATTNAME AS COLUMNS_NAME
	, COMMENT.DESCRIPTION AS COLUMNS_COMMENT
FROM
	 PG_STAT_ALL_TABLES TABLES
INNER JOIN
	PG_ATTRIBUTE COLUMNS
ON
	COLUMNS.ATTRELID = TABLES.RELID
LEFT JOIN
	PG_DESCRIPTION COMMENT
ON 
	COLUMNS.ATTRELID = COMMENT.OBJOID
	AND COMMENT.OBJSUBID = COLUMNS.ATTNUM
WHERE 
	TABLES.SCHEMANAME = 'public'
ORDER BY
	COMMENT.OBJSUBID
